# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'EyezonSDK-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "EyezonSDK"
  # Pods for EyezonSDK-Test

end
