-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQganq4MkteIHSbUv2D
z6W9aoO9BeFJZoeZeSWCLaIEMHegCgYIKoZIzj0DAQehRANCAASS5fGveSX9KwWe
FzNCAApBULSkjFy4nSEJ204LoG8F2+AsptqhOl3OBB4HMuVtm6qFwmH0p9M5whzP
UiAw3HNs
-----END PRIVATE KEY-----